---
Name: silverstripe-helpers
---
Controller:
  extensions:
    - SS_RelativeAssetsResponseExtension

DataList:
  extensions:
    - DataListExtension

ArrayList:
  extensions:
    - DataListExtension

SiteTree:
  extensions:
    - ExtraPageFieldsExtension

SiteConfig:
  extensions:
    - WebFoxSiteConfig

Image:
  extensions:
    - ImageExtension

Link:
  extensions:
    - LinkExtension

#SiteTree:
#  extensions:
#    - FooterMenuExtension
